# Generated by Django 4.1.4 on 2022-12-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=75)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=75)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veterinarios')),
            ],
        ),
    ]
